logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/E85Addict/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
build-mode = "both"
module-prop-name = "youtube-E85"
patches-source = "E85Addict/revanced-patches"
excluded-patches = ""
included-patches = ""
patcher-args = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
enabled = true
build-mode = "both"
module-prop-name = "music-E85"
arch = "arm64-v8a"
patches-source = "E85Addict/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[GooglePhotos]
enabled = false
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

# dont build on gh actions (https://github.com/j-hc/revanced-magisk-module/issues/554)
[Music-Extended]
enabled = true
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
module-prop-name = "music-E85"
arch = "arm64-v8a"
included-patches = "'Custom header for YouTube Music'"
patcher-args = "--legacy-options options.json"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
module-prop-name = "youtube-E85"
included-patches = "'Custom header for YouTube'"
patcher-args = "--legacy-options options.json"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Twitter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
enabled = true
build-mode = "both"
version = "37.0.4"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/e85-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[YouTube-Custom]
enabled = true
exclusive-patches = true
module-prop-name = "youtube-E85"
build-mode = "module"
patches-source = "E85Addict/revanced-patches"
included-patches = """\
    'Custom branding' 'Change header' 'Disable precise seeking gesture' 'Remove background playback restrictions' \
    'Seekbar tapping' 'Video ads' 'Hide ads' 'Enable tablet layout' 'Restore old video quality menu' 'Seekbar thumbnails' \
    'Return YouTube Dislike' 'Miniplayer' 'Theme' 'SponsorBlock' \
    """
patcher-args = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/e85-apks/apks/com.google.android.youtube"

[Telegram]
enabled = true
build-mode = "both"
patches-source = "Aunali321/ReVancedExperiments"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram/"
version = "auto"

[Instagram]
enabled = true
build-mode = "both"
patches-source = "Aunali321/ReVancedExperiments"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
version = "auto"
arch = "arm64-v8a"  
